<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>SmartPrepModern</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Windows" />
    <Import Include="System.Windows.Controls" />
    <Import Include="System.Windows.Data" />
    <Import Include="System.Windows.Documents" />
    <Import Include="System.Windows.Input" />
    <Import Include="System.Windows.Media" />
    <Import Include="System.Windows.Media.Imaging" />
    <Import Include="System.Windows.Navigation" />
    <Import Include="System.Windows.Shapes" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <!-- <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3065.39" /> -->
  </ItemGroup>

  <!-- WATCH XAML files so dotnet watch rebuilds -->
  <ItemGroup>
    <Watch Include="**\*.xaml" />
    <Watch Include="**\*.xaml.vb" />
  </ItemGroup>
</Project>
